version: '3.8'

services:
  nginx:
    env_file:
      - .env
    build:
      context: ./requirements/nginx
    image: nginx:v1
    container_name: nginx
    ports:
      - "443:443"
      - "9090:9090"
    volumes:
      - "wp:/wordpress"
      - "/home/oaboulgh/data/adminer:/adminer"
    networks:
      - my-net
    depends_on:
      - wordpress
    restart: always
  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress:v1
    expose:
      - 9000
    volumes:
      - "wp:/wordpress"
    networks:
      - my-net
    depends_on:
      - mariadb
    restart: always
  mariadb:
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:v1
    ports:
      - "3306:3306"
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - my-net
    restart: always
  adminer:
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer:v1
    expose:
      - 9001
    volumes:
      - "adminer:/adminer"
    networks:
      - my-net
    depends_on:
      - wordpress
    restart: always
  ftp:
    env_file:
      - .env
    build:
      context: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp:v1
    ports:
      - "30000-30100:30000-30100"
      - "21:21"
    volumes:
      - "wp:/ptr"
    networks:
      - my-net
    restart: always
  cadvisor:
    build:
      context: ./requirements/bonus/cadvisor
    container_name: cadvisor
    image: cadvisor:v1
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - my-net
    restart: always
  redis:
    build:
      context: ./requirements/bonus/redis
    container_name: redis
    image: redis:v1
    expose:
      - 6379
    networks:
      - my-net
    depends_on:
      - wordpress
    restart: always
  site:
    build:
      context: ./requirements/bonus/static_site
    container_name: static_site
    image: static_site:v1
    ports:
      - "9191:9191"
    volumes:
      - /home/oaboulgh/data/site:/site
    restart: always

networks:
  my-net:
    driver: bridge

volumes:
  db:
    driver_opts:
      type: none
      device: /home/oaboulgh/data/mariadb
      o: bind
  wp:
    driver_opts:
      type: none
      device: /home/oaboulgh/data/wordpress
      o: bind
  adminer:
    driver_opts:
      type: none
      device:  /home/oaboulgh/data/adminer
      o: bind
