version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "80:80"
    volumes:
      - "./wordpress:/wordpress"
    networks:
      - my-net
  wordpress:
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
    expose:
      - 9000
    volumes:
      - "./wordpress:/wordpress"
    networks:
      - my-net
  mariadb:
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
    ports:
      - "3306:3306"
    networks:
      - my-net
  ftp:
    build:
      context: ./requirements/bonus/ftp
    ports:
      - "20:20"
      - "21:21"
      - "22:22"
    # expose:
    #   - 21
    #   - 20
    volumes:
      - "./wordpress:/ptr"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge